In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
df = pd.read_csv("housing.csv")
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500,4000,2,1,1,yes,no,no,no,no,0,no
2,49500,3060,3,1,1,yes,no,no,no,no,0,no
3,60500,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000,6000,3,1,2,yes,no,no,no,yes,1,no

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    int64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: int64(6), object(6)
memory usage: 51.3+ KB

In [28]:
df.describe()

,price,lotsize,bedrooms,bathrms,stories,garagepl
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,68121.597070,5150.265568,2.965201,1.285714,1.807692,0.692308
std,26702.670926,2168.158725,0.737388,0.502158,0.868203,0.861307
min,25000.000000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,49125.000000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,62000.000000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,82000.000000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,190000.000000,16200.000000,6.000000,4.000000,4.000000,3.000000

In [32]:
data = df.copy()
cols_to_norm = ['price','lotsize','bedrooms','bathrms','stories','garagepl']
data[cols_to_norm] = data[cols_to_norm].apply(lambda x: (x-x.min()) / (x.max() - x.min()))
print(data["price"])

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,0.103030,0.288660,0.4,0.000000,0.333333,yes,no,yes,no,no,0.333333,no
1,0.081818,0.161512,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
2,0.148485,0.096907,0.4,0.000000,0.000000,yes,no,no,no,no,0.000000,no
3,0.215152,0.343643,0.4,0.000000,0.333333,yes,yes,no,no,no,0.000000,no
4,0.218182,0.323711,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
5,0.248485,0.172509,0.4,0.000000,0.000000,yes,yes,yes,no,yes,0.000000,no
6,0.248485,0.153265,0.4,0.333333,0.333333,yes,no,yes,no,no,0.666667,no
7,0.266667,0.172509,0.4,0.000000,0.666667,yes,no,no,no,no,0.000000,no
8,0.356364,0.216495,0.4,0.000000,0.000000,yes,yes,yes,no,no,0.000000,no
9,0.384848,0.264605,0.4,0.333333,1.000000,yes,yes,no,no,yes,0.333333,no
10,0.393939,0.381443,0.4,0.333333,0.000000,yes,no,yes,no,yes,1.000000,no
11,0.033333,0.092784,0.2,0.000000,0.000000,no,no,no,no,no,0.000000,no
12,0.012121,0.003436,0.4,0.000000,0.333333,yes,no,no,no,no,0.000000,no
13,0.066667,0.084536,0.4,0.000000,0.000000,no,no,no,no,no,0.000000,no
14,0.072727,0.134021,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
15,0.078182,0.105498,0.2,0.000000,0.000000,yes,no,no,no,yes,0.000000,no
16,0.093939,0.113402,0.4,0.000000,0.333333,no,no,no,no,no,0.333333,no
17,0.095455,0.243986,0.6,0.000000,0.666667,yes,no,no,no,no,0.000000,no
18,0.121212,0.123711,0.0,0.000000,0.000000,yes,no,no,no,no,0.000000,no
19,0.121212,0.160550,0.2,0.333333,0.000000,no,yes,yes,no,no,0.333333,no
20,0.142424,0.215464,0.4,0.000000,0.333333,yes,yes,yes,no,yes,0.333333,no
21,0.247879,0.196564,0.6,0.333333,0.333333,yes,no,yes,no,no,0.000000,no
22,0.078182,0.161512,0.4,0.000000,0.333333,yes,no,no,no,yes,0.000000,no
23,0.078788,0.156976,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
24,0.103030,0.227491,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
25,0.104848,0.092784,0.2,0.000000,0.333333,yes,no,no,no,no,0.000000,no
26,0.112121,0.147766,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
27,0.115152,0.227491,0.2,0.000000,0.000000,yes,no,yes,no,yes,0.000000,no
28,0.118182,0.092784,0.4,0.000000,0.000000,no,no,no,no,yes,0.000000,no
29,0.120606,0.195876,0.4,0.000000,0.333333,yes,no,no,no,yes,0.000000,no
30,0.121212,0.127148,0.2,0.000000,0.000000,no,no,yes,no,no,0.000000,no
31,0.139394,0.127148,0.6,0.000000,0.333333,yes,no,no,no,yes,0.666667,no
32,0.145455,0.161512,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
33,0.160606,0.195876,0.2,0.000000,0.000000,yes,no,no,no,no,0.000000,no
34,0.218182,0.323711,0.2,0.000000,0.333333,yes,no,no,no,no,0.000000,no
35,0.218182,0.195876,0.2,0.000000,0.000000,yes,no,no,no,yes,0.666667,no
36,0.222424,0.163711,0.2,0.000000,0.000000,yes,no,yes,no,no,0.000000,no
37,0.254545,0.241924,0.4,0.000000,1.000000,yes,no,no,no,yes,0.000000,no
38,0.345455,0.257732,0.6,0.333333,0.333333,yes,no,no,no,yes,0.666667,no
39,0.178788,0.103093,0.2,0.333333,0.000000,no,no,yes,no,no,0.000000,no
40,0.251515,0.143986,0.4,0.000000,0.333333,yes,no,yes,no,no,0.000000,no
41,0.272727,0.197251,0.4,0.000000,0.333333,yes,no,yes,no,yes,0.000000,no
42,0.345455,0.205498,0.6,0.000000,0.333333,yes,no,no,no,no,0.333333,no
43,0.406061,0.476289,0.8,0.666667,0.333333,yes,no,no,no,no,0.666667,no
44,0.078788,0.024055,0.2,0.000000,0.333333,yes,no,no,no,no,0.000000,no
45,0.115152,0.035052,0.4,0.000000,0.333333,no,no,yes,no,no,0.000000,no
46,0.096970,0.095533,0.2,0.000000,0.000000,no,no,no,no,no,0.000000,no
47,0.109091,0.098969,0.4,0.000000,0.333333,no,no,no,no,no,0.000000,no
48,0.139394,0.227491,0.6,0.000000,0.666667,no,no,no,no,no,0.000000,no
49,0.180606,0.116838,0.4,0.000000,0.333333,yes,no,no,no,no,0.000000,no

In [30]:
data.describe()

            price     lotsize    bedrooms     bathrms     stories    garagepl
count  546.000000  546.000000  546.000000  546.000000  546.000000  546.000000
mean     0.261343    0.240568    0.393040    0.095238    0.269231    0.230769
std      0.161834    0.149014    0.147478    0.167386    0.289401    0.287102
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.146212    0.134021    0.200000    0.000000    0.000000    0.000000
50%      0.224242    0.202749    0.400000    0.000000    0.333333    0.000000
75%      0.345455    0.323711    0.400000    0.333333    0.333333    0.333333
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

In [31]:
data.isnull().sum()

price       0
lotsize     0
bedrooms    0
bathrms     0
stories     0
driveway    0
recroom     0
fullbase    0
gashw       0
airco       0
garagepl    0
prefarea    0
dtype: int64

In [ ]:
Predictors = ["lotsize","bedrooms","bathrms","stories","garagepl"]
target = ["price"]

np.random.seed(0)
split_data = np.split(data,[int(.7*len(data)), int(.3*len(data))])
(train_x,train_y),(valid_x,valid_y),(test_x,test_y) = [[d[Predictors].to_numpy(),d[target].to_numpy()] for d in split_data]

In [ ]:
import math

def init_params(predictors):
    np.random.seed(0)
    weights = np.random.randn(predictors,1)
    biases = np.ones((1,1))
    return [weights,biases]

In [ ]:
init_params(5)